Feature/alt 99
VeriBlock/alt-integration pull request #69
Opened 2019-12-03 12:49 UTC by Mr-Leshiy

WIP

2019-12-03 13:49 UTC, blackyblack requested changes

2019-12-03 13:49 UTC, blackyblack commented on alt-integration-adapter-java/src/main/java/org/veriblock/protoservice/VeriBlockSecurityProtoService.java
> +                bitcoinBlocks.add(block);
Use https://github.com/VeriBlock/alt-integration/blob/develop/alt-integration-adapter-java/src/main/java/org/veriblock/protoconverters/BitcoinBlockProtoConverter.java#L35 instead.

2019-12-03 13:49 UTC, blackyblack commented on alt-integration-adapter-java/src/main/java/org/veriblock/protoservice/VeriBlockSecurityProtoService.java
> +    public static VeriBlockMessages.GeneralReply updateContext(VeriBlockMessages.UpdateContextRequest request) {
protoservice package should not contain library code. It should redirect calls to the security service instance.

2019-12-03 13:51 UTC, Warchant commented
@Mr-Leshiy  https://github.com/VeriBlock/alt-integration-proto/releases/tag/v3 you can use v3 now

2019-12-04 07:52 UTC, Warchant approved these changes

2019-12-04 08:15 UTC, merged