Feature/refactor block repository
VeriBlock/alt-integration pull request #9
Opened 2019-10-25 07:59 UTC by eu321

2019-10-25 10:02 UTC, blackyblack requested changes

2019-10-25 10:02 UTC, blackyblack commented on reference-lib/src/test/java/org/veriblock/integrations/sqlite/SqliteBitcoinBlocksTableTest.java
> +        // try to delete non existing recorss. See that nothing happens.
records

2019-10-25 13:06 UTC, eu321 commented on reference-lib/src/test/java/org/veriblock/integrations/sqlite/SqliteBitcoinBlocksTableTest.java
> +        // try to delete non existing recorss. See that nothing happens.
lol

2019-10-28 09:18 UTC, eu321 commented
already merged indirectly via another PR that was based on this one

2019-10-28 09:18 UTC, closed without merging